# PostgreSQL database container
version: '3'
services:
  postgresql:
    container_name: postgresql-container
    image: postgres:latest
    volumes:
      - db_persdata:/var/lib/postgrespers
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: admin12345678
    networks:
      - default
networks:
  default:
volumes:
  db_persdata : {}